//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeditSolution.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MeditSolution.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string forgot {
            get {
                return ResourceManager.GetString("forgot", resourceCulture);
            }
        }
        
        internal static string forgotButton {
            get {
                return ResourceManager.GetString("forgotButton", resourceCulture);
            }
        }
        
        internal static string sendnewpassword {
            get {
                return ResourceManager.GetString("sendnewpassword", resourceCulture);
            }
        }
        
        internal static string wrongsendnewpassword {
            get {
                return ResourceManager.GetString("wrongsendnewpassword", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string tutorial0 {
            get {
                return ResourceManager.GetString("tutorial0", resourceCulture);
            }
        }
        
        internal static string tutorial1 {
            get {
                return ResourceManager.GetString("tutorial1", resourceCulture);
            }
        }
        
        internal static string tutorial2 {
            get {
                return ResourceManager.GetString("tutorial2", resourceCulture);
            }
        }
        
        internal static string tutorial3 {
            get {
                return ResourceManager.GetString("tutorial3", resourceCulture);
            }
        }
        
        internal static string tutorial4 {
            get {
                return ResourceManager.GetString("tutorial4", resourceCulture);
            }
        }
        
        internal static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        internal static string enteremail {
            get {
                return ResourceManager.GetString("enteremail", resourceCulture);
            }
        }
        
        internal static string enterpassword {
            get {
                return ResourceManager.GetString("enterpassword", resourceCulture);
            }
        }
        
        internal static string connectfb {
            get {
                return ResourceManager.GetString("connectfb", resourceCulture);
            }
        }
        
        internal static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        internal static string completeregister {
            get {
                return ResourceManager.GetString("completeregister", resourceCulture);
            }
        }
        
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        internal static string skip {
            get {
                return ResourceManager.GetString("skip", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string letsgo {
            get {
                return ResourceManager.GetString("letsgo", resourceCulture);
            }
        }
        
        internal static string nothanks {
            get {
                return ResourceManager.GetString("nothanks", resourceCulture);
            }
        }
        
        internal static string Initiate {
            get {
                return ResourceManager.GetString("Initiate", resourceCulture);
            }
        }
        
        internal static string subscribedprograms {
            get {
                return ResourceManager.GetString("subscribedprograms", resourceCulture);
            }
        }
        
        internal static string otherprograms {
            get {
                return ResourceManager.GetString("otherprograms", resourceCulture);
            }
        }
        
        internal static string tab1 {
            get {
                return ResourceManager.GetString("tab1", resourceCulture);
            }
        }
        
        internal static string tab2 {
            get {
                return ResourceManager.GetString("tab2", resourceCulture);
            }
        }
        
        internal static string tab3 {
            get {
                return ResourceManager.GetString("tab3", resourceCulture);
            }
        }
        
        internal static string tab4 {
            get {
                return ResourceManager.GetString("tab4", resourceCulture);
            }
        }
        
        internal static string program {
            get {
                return ResourceManager.GetString("program", resourceCulture);
            }
        }
        
        internal static string seances {
            get {
                return ResourceManager.GetString("seances", resourceCulture);
            }
        }
        
        internal static string takebreak {
            get {
                return ResourceManager.GetString("takebreak", resourceCulture);
            }
        }
        
        internal static string yoursetting {
            get {
                return ResourceManager.GetString("yoursetting", resourceCulture);
            }
        }
        
        internal static string chooselanguage {
            get {
                return ResourceManager.GetString("chooselanguage", resourceCulture);
            }
        }
        
        internal static string choosevoice {
            get {
                return ResourceManager.GetString("choosevoice", resourceCulture);
            }
        }
        
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        internal static string doyouknow {
            get {
                return ResourceManager.GetString("doyouknow", resourceCulture);
            }
        }
        
        internal static string doyouknowdetail {
            get {
                return ResourceManager.GetString("doyouknowdetail", resourceCulture);
            }
        }
        
        internal static string nomeditation {
            get {
                return ResourceManager.GetString("nomeditation", resourceCulture);
            }
        }
        
        internal static string startinitiate {
            get {
                return ResourceManager.GetString("startinitiate", resourceCulture);
            }
        }
        
        internal static string evolution {
            get {
                return ResourceManager.GetString("evolution", resourceCulture);
            }
        }
        
        internal static string tonextlevel {
            get {
                return ResourceManager.GetString("tonextlevel", resourceCulture);
            }
        }
        
        internal static string hourmeditated {
            get {
                return ResourceManager.GetString("hourmeditated", resourceCulture);
            }
        }
        
        internal static string continousactivity {
            get {
                return ResourceManager.GetString("continousactivity", resourceCulture);
            }
        }
        
        internal static string atmoment {
            get {
                return ResourceManager.GetString("atmoment", resourceCulture);
            }
        }
        
        internal static string maximum {
            get {
                return ResourceManager.GetString("maximum", resourceCulture);
            }
        }
        
        internal static string bravo {
            get {
                return ResourceManager.GetString("bravo", resourceCulture);
            }
        }
        
        internal static string bravodetail {
            get {
                return ResourceManager.GetString("bravodetail", resourceCulture);
            }
        }
        
        internal static string bravodetail2 {
            get {
                return ResourceManager.GetString("bravodetail2", resourceCulture);
            }
        }
        
        internal static string bravodetail3 {
            get {
                return ResourceManager.GetString("bravodetail3", resourceCulture);
            }
        }
        
        internal static string medover {
            get {
                return ResourceManager.GetString("medover", resourceCulture);
            }
        }
        
        internal static string medoverdetail {
            get {
                return ResourceManager.GetString("medoverdetail", resourceCulture);
            }
        }
        
        internal static string explorecatalogue {
            get {
                return ResourceManager.GetString("explorecatalogue", resourceCulture);
            }
        }
        
        internal static string congrats {
            get {
                return ResourceManager.GetString("congrats", resourceCulture);
            }
        }
        
        internal static string congratsdetail {
            get {
                return ResourceManager.GetString("congratsdetail", resourceCulture);
            }
        }
        
        internal static string congratsdetail2 {
            get {
                return ResourceManager.GetString("congratsdetail2", resourceCulture);
            }
        }
        
        internal static string nextseance {
            get {
                return ResourceManager.GetString("nextseance", resourceCulture);
            }
        }
        
        internal static string backtocatalogue {
            get {
                return ResourceManager.GetString("backtocatalogue", resourceCulture);
            }
        }
        
        internal static string reminders {
            get {
                return ResourceManager.GetString("reminders", resourceCulture);
            }
        }
        
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        internal static string coherentbreathing {
            get {
                return ResourceManager.GetString("coherentbreathing", resourceCulture);
            }
        }
        
        internal static string nocycles {
            get {
                return ResourceManager.GetString("nocycles", resourceCulture);
            }
        }
        
        internal static string noduration {
            get {
                return ResourceManager.GetString("noduration", resourceCulture);
            }
        }
        
        internal static string silentmeditation {
            get {
                return ResourceManager.GetString("silentmeditation", resourceCulture);
            }
        }
        
        internal static string chooseduration {
            get {
                return ResourceManager.GetString("chooseduration", resourceCulture);
            }
        }
        
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        internal static string subscription {
            get {
                return ResourceManager.GetString("subscription", resourceCulture);
            }
        }
        
        internal static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        internal static string annualy {
            get {
                return ResourceManager.GetString("annualy", resourceCulture);
            }
        }
        
        internal static string termscondition {
            get {
                return ResourceManager.GetString("termscondition", resourceCulture);
            }
        }
        
        internal static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        internal static string isubscribe {
            get {
                return ResourceManager.GetString("isubscribe", resourceCulture);
            }
        }
        
        internal static string restorepurchase {
            get {
                return ResourceManager.GetString("restorepurchase", resourceCulture);
            }
        }
        
        internal static string mysubscription {
            get {
                return ResourceManager.GetString("mysubscription", resourceCulture);
            }
        }
        
        internal static string subscriptionstarted {
            get {
                return ResourceManager.GetString("subscriptionstarted", resourceCulture);
            }
        }
        
        internal static string seeterms {
            get {
                return ResourceManager.GetString("seeterms", resourceCulture);
            }
        }
        
        internal static string unsubscribe {
            get {
                return ResourceManager.GetString("unsubscribe", resourceCulture);
            }
        }
        
        internal static string youremail {
            get {
                return ResourceManager.GetString("youremail", resourceCulture);
            }
        }
        
        internal static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        internal static string myaccount {
            get {
                return ResourceManager.GetString("myaccount", resourceCulture);
            }
        }
        
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        internal static string mediter {
            get {
                return ResourceManager.GetString("mediter", resourceCulture);
            }
        }
        
        internal static string menureminder {
            get {
                return ResourceManager.GetString("menureminder", resourceCulture);
            }
        }
        
        internal static string cgu {
            get {
                return ResourceManager.GetString("cgu", resourceCulture);
            }
        }
        
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        internal static string videos {
            get {
                return ResourceManager.GetString("videos", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string accountexists {
            get {
                return ResourceManager.GetString("accountexists", resourceCulture);
            }
        }
        
        internal static string erroraccountcreate {
            get {
                return ResourceManager.GetString("erroraccountcreate", resourceCulture);
            }
        }
        
        internal static string incorrectcombo {
            get {
                return ResourceManager.GetString("incorrectcombo", resourceCulture);
            }
        }
        
        internal static string requestfailed {
            get {
                return ResourceManager.GetString("requestfailed", resourceCulture);
            }
        }
        
        internal static string programmes {
            get {
                return ResourceManager.GetString("programmes", resourceCulture);
            }
        }
        
        internal static string buyterms {
            get {
                return ResourceManager.GetString("buyterms", resourceCulture);
            }
        }
        
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        internal static string SubscriptionThanks {
            get {
                return ResourceManager.GetString("SubscriptionThanks", resourceCulture);
            }
        }
        
        internal static string SubscriptionRequired {
            get {
                return ResourceManager.GetString("SubscriptionRequired", resourceCulture);
            }
        }
        
        internal static string SubscribeMessage {
            get {
                return ResourceManager.GetString("SubscribeMessage", resourceCulture);
            }
        }
        
        internal static string SubscribeNow {
            get {
                return ResourceManager.GetString("SubscribeNow", resourceCulture);
            }
        }
        
        internal static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        internal static string ErrorMessageSubscription {
            get {
                return ResourceManager.GetString("ErrorMessageSubscription", resourceCulture);
            }
        }
        
        internal static string UnsubscribeWarning {
            get {
                return ResourceManager.GetString("UnsubscribeWarning", resourceCulture);
            }
        }
        
        internal static string MeditationChat1 {
            get {
                return ResourceManager.GetString("MeditationChat1", resourceCulture);
            }
        }
        
        internal static string MeditationChat2 {
            get {
                return ResourceManager.GetString("MeditationChat2", resourceCulture);
            }
        }
        
        internal static string MeditationChat3 {
            get {
                return ResourceManager.GetString("MeditationChat3", resourceCulture);
            }
        }
        
        internal static string MeditationChat4 {
            get {
                return ResourceManager.GetString("MeditationChat4", resourceCulture);
            }
        }
        
        internal static string MeditationChat5 {
            get {
                return ResourceManager.GetString("MeditationChat5", resourceCulture);
            }
        }
        
        internal static string MeditationChat6 {
            get {
                return ResourceManager.GetString("MeditationChat6", resourceCulture);
            }
        }
        
        internal static string MeditationChat7 {
            get {
                return ResourceManager.GetString("MeditationChat7", resourceCulture);
            }
        }
        
        internal static string MeditationChat8 {
            get {
                return ResourceManager.GetString("MeditationChat8", resourceCulture);
            }
        }
        
        internal static string MeditationChat9 {
            get {
                return ResourceManager.GetString("MeditationChat9", resourceCulture);
            }
        }
        
        internal static string MeditationChat10 {
            get {
                return ResourceManager.GetString("MeditationChat10", resourceCulture);
            }
        }
        
        internal static string ProgramPaidThanks {
            get {
                return ResourceManager.GetString("ProgramPaidThanks", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string NotificationHeader {
            get {
                return ResourceManager.GetString("NotificationHeader", resourceCulture);
            }
        }
        
        internal static string NotificationContent {
            get {
                return ResourceManager.GetString("NotificationContent", resourceCulture);
            }
        }
        
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        internal static string downloadFailed {
            get {
                return ResourceManager.GetString("downloadFailed", resourceCulture);
            }
        }
        
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        internal static string ActiveIntNeeded {
            get {
                return ResourceManager.GetString("ActiveIntNeeded", resourceCulture);
            }
        }

        internal static string seance
        {
            get
            {
                return ResourceManager.GetString("seance", resourceCulture);
            }
        }

        internal static string minute
        {
            get
            {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }

        internal static string seconds
        {
            get
            {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }

        internal static string pickduration
        {
            get
            {
                return ResourceManager.GetString("pickduration", resourceCulture);
            }
        }
    }
}
